### ISSUE TITLE
Make repo a GitHub template

### ISSUE THREAD

**Issue by mohan-cao** [Phoqe/react-material-ui-firebase#148]
**Is your feature request related to a problem? Please describe.**
Would be nice to directly clone a repo in GitHub with a click of a button when I don't have access to a CLI (or when I'm not actively contributing fixes)

**Describe the solution you'd like**
Toggle the "Template repository" checkbox in the repo settings

**Describe alternatives you've considered**
I could potentially fork the repo, but that's really not an option when I want to use this as a template and not for contribution.

**Comment by Phoqe** [comment]
Hmm... there seems to be an issue with GitHub concerning this option. I can't even count how many times I've enabled this option but it keeps turning off. I have enabled it again but I will keep this issue opened as I am going to contact GitHub.

**Comment by Phoqe** [comment]
For new projects I would recommend cloning the template (via GitHub if you'd like) and set-up this repository as an upstream. That way you can pull in new changes to the template and merge it with your existing code base. I will expand upon this subject in the 2.0 instructions. Thank you for considering this template for your project.

**Comment by Phoqe** [comment]
I have contacted GitHub and am awaiting their response. I will update this issue with info as it becomes available.

**Comment by Phoqe** [comment]
I found out what caused it and have reported it to GitHub. Closing this issue, thank you for noticing @mohan-cao.
