### ISSUE TITLE
Stale Firebase Admin Authentication API Errors?

### ISSUE THREAD

**Issue by brennanfife** [Phoqe/react-material-ui-firebase#268]
Believe two of the auth errors ('user-disabled' and 'wrong-password') inside the switch statement of signInDialog's signIn method might be stale... I wasn't able to find them in Firebase's API doc... might be due to an update..?

**Comment by Phoqe** [comment]
https://firebase.google.com/docs/reference/js/firebase.auth.Auth#error-codes_12
