### ISSUE TITLE
SignIn Dialog, Line 135, Unhandled rejection (TypeError): reason is undefined

### ISSUE THREAD

**Issue by Quantmatic** [Phoqe/react-material-ui-firebase#297]
Hi,

Really cool repo!

Just trying to boot up your code, signup works somewhat, user is created in firebase, but the login does not actually happen, end up dropped out to original starter screen

Then if I try to sign in with the user created from the previous step I get:
SignIn Dialog, Line 135, Unhandled rejection (TypeError): reason is undefined

Any idea why this could be happening?

https://ibb.co/4TPMQBd

**Comment by Phoqe** [comment]
@Quantmatic Which authentication provider are you using (e.g. Facebook, Password) and are you on the latest version (v2.1.0 or master)?

**Comment by Quantmatic** [comment]
I followed the instructions in the readme.md

git clone https://github.com/Phoqe/react-material-ui-firebase.git

I'm in the master branch, just using email/pass auth

**Comment by Phoqe** [comment]
I will take a look!

**Comment by Phoqe** [comment]
@Quantmatic Try these security rules for Firestore:
```
service cloud.firestore {
  match /databases/{database}/documents {
    match /users/{uid} {
      allow get: if request.auth.uid != null;
      allow list: if request.auth.uid != null;
      
      allow create: if request.auth.uid != null &&
                    request.auth.uid == uid;

      allow update: if request.auth.uid != null &&
                       request.auth.uid == uid;

      allow delete: if request.auth.uid != null &&
                       request.auth.uid == uid;
    }
  }
}
```

**Comment by Quantmatic** [comment]
Now the signIn works with no error, but I'm still not getting to home screen...

The account settings icon top right never appears

And now the signUp dumps with this:

SignUp Dialog, Line 90, Unhandled rejection (TypeError): reason is undefined

https://ibb.co/jkCH70L

**Comment by Phoqe** [comment]
Make sure you’ve deleted the invalid account from Firebase and cleared your browser’s cache.

**Comment by samanyougarg** [comment]
I am getting the same error. Email authentication worked after updating firestore rules but others still give the same error.

**Comment by Quantmatic** [comment]
That worked, but still no home screen, settings icon top right never appears.

On signIn now, a message flashes at the bottom:

'Signed in as undefined'

**Comment by samanyougarg** [comment]
Updating the firebase rules fixed the issue for email/password auth but other methods still don't work.
When I tried Google auth, it added the email on firebase but the app gave an error "Failed to get document because the client is offline."

**Comment by Phoqe** [comment]
Hmm, I will give this more research when I’m home. Expect a patch (v2.1.1) today or tomorrow if I find anything directly related to this.

**Comment by Quantmatic** [comment]
I'm running on Ubuntu 19.04 x64, if that helps any, node 10.16.3

**Comment by samanyougarg** [comment]
@Phoqe  Any updates on this?

**Comment by Phoqe** [comment]
@samanyougarg Haven’t taken a look yet, I was busy with work and exams yesterday. Will take a look today.

**Comment by samanyougarg** [comment]
> @samanyougarg Haven’t taken a look yet, I was busy with work and exams yesterday. Will take a look today.

Cool, no worries. Thanks a lot.

**Comment by Phoqe** [comment]
Preliminary results indicate that README.md is incomplete as my proper setup is working properly. I will test this hypothesis.

**Comment by samanyougarg** [comment]
Yes, you are right. I didn't create the database or define the collections etc.

**Comment by samanyougarg** [comment]
Can you please let me know approx. when you would be able to update the readme? Thank you!

**Comment by Phoqe** [comment]
@samanyougarg I will update it today as soon as I get home. I will also add a setup stepper in HomeContent by default showing how to set it up.

**Comment by samanyougarg** [comment]
> @samanyougarg I will update it today as soon as I get home. I will also add a setup stepper in HomeContent by default showing how to set it up.

Thanks a lot. Really appreciate it.

**Comment by samanyougarg** [comment]
@Phoqe Any updates? I am working on a new project and would love to use this.

**Comment by Phoqe** [comment]
@samanyougarg I was busy yesterday. Can you confirm that creating a database and initializing Storage solved your issue?

**Comment by samanyougarg** [comment]
Yes, that solved the issue. Thank you!

**Comment by Phoqe** [comment]
@samanyougarg Did it solve the issue with auth providers too? E.g. can't sign in properly?

**Comment by samanyougarg** [comment]
Yes it did.

**Comment by brian-henderson** [comment]
@samanyougarg can you provide more details on your solution to this bug? I am having the same issue and would like to use this awesome template as well

**Comment by Phoqe** [comment]
@brian-henderson I will release a more detailed guide soon. Very busy at the moment, but expect one up by the weekend.

**Comment by Phoqe** [comment]
@Quantmatic @samanyougarg @brian-henderson There’s a new README detailing how to setup Firebase and use it in the app on a separate branch, I am not happy with it just yet but I followed it and it’s working. I will continue to improve upon it the next few days and eventually merge it to `master`. https://github.com/Phoqe/react-material-ui-firebase/tree/new-readme

**Comment by Phoqe** [comment]
Closing this issue. Further discussion about improving the setup process can be discussed in #304

**Comment by Quantmatic** [comment]
Works perfectly now, thanks for the update....
