### ISSUE TITLE
Just a quick question

### ISSUE THREAD

**Issue by Njabulo-Mbuli** [Phoqe/react-material-ui-firebase#323]
I found this and thought it was really awesome because I am just jumping into using material with my personal projects. Cloned your project and I am using the code as a great learning tool.

There's something I hoped you could help me understand a little better. When I work with react in development refreshing the page has no issues, but in production it throws a 404 error. My understanding is that the server is responding with a 404 error because it can't handle the route that is being requested. I am wondering how you got around this issue without using a backend language like node, because when I refresh the page on your project in production it does not respond with a 404 error.

I would appreciate any kind of help on this topic.

**Comment by Phoqe** [comment]
Hello @Njabulo-Mbuli, thank you for using my project.

It could be because you haven’t set the `homepage` property in `package.json`. The current README is somewhat outdated and I am working on a rewrite. Sorry for the confusion and let me know if that works.
