### ISSUE TITLE
API key exposed (npm package)

### ISSUE THREAD

**Issue by Eli-Goldberg** [phoqe/react-material-ui-firebase#340]
Hi,
I've stumbled upon your project - and it seems the firebase api keys are exposed.
Is this normal?

Just out of curiosity :)
Thanks.

**Comment by phoqe** [comment]
Yes, this is normal. Access is controlled through Security Rules established in the Firebase project.

**Comment by Eli-Goldberg** [comment]
cool, TIL :)
