### ISSUE TITLE
Alignment issue with first button in AuthProviderList.js

### ISSUE THREAD

**Issue by grempe** [Phoqe/react-material-ui-firebase#83]
There is an alignment issue with the left side of the first button shown in this component.

See:
https://cl.ly/08dab4cd9678

It's always the first button shown that has the issue.

**Comment by Phoqe** [comment]
Thank you for going through and testing the application, it hasn't seen the light of day for a lot of people yet. I think this issue has to do with the upgrade to Material-UI 4, I will take a look at it.

**Comment by Phoqe** [comment]
Fixed in #85.
