### ISSUE TITLE
Incorporate Firebase Firestore 

### ISSUE THREAD

**Issue by grempe** [Phoqe/react-material-ui-firebase#84]
I see you closed this issue. I'd ask for you to consider re-opening and providing simple and idiomatic example of Cloud Firestore usage in the context of React.

A potentially good place in the current app's context to demonstrate this would perhaps be in the theme color preferences, persisting them in the DB and loading them on running the app in any browser where you sign in.

https://github.com/Phoqe/react-material-ui-firebase/issues/37

**Comment by Phoqe** [comment]
I closed the issue since I didn't have any proper example to use but what you're suggesting is already an issue (#70). There will be a checkbox or switch (when on mobile) to turn on and turn off syncing, appearance settings will be bound to each account's UID.

**Comment by Phoqe** [comment]
Appearance settings sync will be added in conjunction with a new settings dialog I'm working on, it will fix most active issues on here.

**Comment by Phoqe** [comment]
@grempe There is a new sign in and sign up dialog available in the `dialog-host` branch. They're the groundwork for a new settings dialog which will feature more complex user data such as first and last names, username, and gender. The branch, along with the new settings dialog, will be merged and available in `master` at the end of the week.

**Comment by grempe** [comment]
Thanks for the heads up. I look forward to checking it out.

**Comment by Phoqe** [comment]
I‘ve integrated Firebase Firestore syncing but am currently revising the theme application process and improving general performance before merging it.
